name: barq_player
description: "Barq Player - Professional IPTV Streaming Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  provider: ^6.1.1
  
  http: ^1.2.0
  dio: ^5.4.0
  
  video_player: ^2.8.2
  chewie: ^1.7.4
  
  shared_preferences: ^2.2.2
  
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  iconsax: ^0.0.8
  
  intl: ^0.20.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
